package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Dalvan
 */
public class ViewVisualizarConciliacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaBuscarCliente
     */
    public ViewVisualizarConciliacao() {
        initComponents();
        setLocationRelativeTo(null);
        atualizar();
    }
    /**
     * variaveis static criadas para a tela poder ser fechada
     * e elas não perderem seu valor 
     */
    Boolean cadastrar = true;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        txtProcurar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome:", "Telefone:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblClienteKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        txtProcurar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProcurarKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/projeto/dalvan/prbar/icones/images.png"))); // NOI18N
        jLabel2.setText("Procurar:");

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        //jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/projeto/dalvan/prbar/icones/import-icon (Custom).png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(214)
        					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(txtProcurar, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 651, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(273)
        					.addComponent(jButton2)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(42)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(txtProcurar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel2)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(92)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        			.addComponent(jButton2)
        			.addGap(172))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tblClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblClienteKeyPressed
        
        //Validação feita para se o usuario clicar na tecla enter ele excuta o
        if (evt.getKeyCode() == 10) {
            Integer linha = tblCliente.getSelectedRow();
            Integer id = Integer.parseInt(tblCliente.getValueAt(linha, 0).toString());
//            ClienteDAO dao = new ClienteDAO();
//            objCliente = dao.getById(id);
//            TelaVendas tela = new TelaVendas();
            //tela.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_tblClienteKeyPressed
    private void txtProcurarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProcurarKeyReleased
         /**
        *  acao feita para procurar um cliente na tabela atraves de seu nome
        *  é criada uma String e ela é setada ,depois a classe ClienteDAO é instanciada 
        * e é chamado o metodo getAllBuscarPorNome mandando o String
        */
//        String nome = txtProcurar.getText();
//        ClienteDAO dao = new ClienteDAO();
//        List<Cliente> lista = dao.buscarPorNome(nome);
//        DefaultTableModel model = (DefaultTableModel) this.tblCliente.getModel();
//        model.setRowCount(lista.size());
//        for (int i = 0; i < lista.size(); i++) {
//            model.setValueAt(lista.get(i).getIdCliente(), i, 0);
//            model.setValueAt(lista.get(i).getNome(), i, 1);
//            model.setValueAt(lista.get(i).getTelefone(), i, 2);
//        }
    }//GEN-LAST:event_txtProcurarKeyReleased
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
     /**
     *  Metodo utilizado para atualizar a tabela de clientes,
     *  onde a classe ClienteDAO é instanciada e é chamado o
     * metodo get.all que retorna uma lista de clientes que
     * ja estao cadastrados no banco 
     */
    private void atualizar() {
//        ClienteDAO dao = new ClienteDAO();
//        List<Cliente> lista = dao.getAll();
//        DefaultTableModel model = (DefaultTableModel) this.tblCliente.getModel();
//        model.setRowCount(lista.size());
//        for (int i = 0; i < lista.size(); i++) {
//            model.setValueAt(lista.get(i).getIdCliente(), i, 0);
//            model.setValueAt(lista.get(i).getNome(), i, 1);
//            model.setValueAt(lista.get(i).getTelefone(), i, 2);
//        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVisualizarConciliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVisualizarConciliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVisualizarConciliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVisualizarConciliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVisualizarConciliacao().setVisible(true);
            }
        });
    }
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtProcurar;
    // End of variables declaration//GEN-END:variables
}
