package view;

import java.awt.Image;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.ImageIcon;

public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Programa Bar");
        Image imagem;
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        btnSair.setIcon(new ImageIcon(ViewPrincipal.class.getResource("/icon/cancel-icon (Custom).png")));
        btnImportacao = new javax.swing.JButton();
        btnImportacao.setIcon(new ImageIcon(ViewPrincipal.class.getResource("/icon/Find-icon2 (Custom).png")));
        btnListarCartoes = new javax.swing.JButton();
        btnListarCartoes.setIcon(new ImageIcon(ViewPrincipal.class.getResource("/icon/Find-icon (Custom).png")));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnImportacao2 = new javax.swing.JMenu();
        btnListarCartoes2 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSair.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        //btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/projeto/dalvan/prbar/icones/cancel-icon (Custom).png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnImportacao.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        //btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/projeto/dalvan/prbar/icones/people-icon.png"))); // NOI18N
        btnImportacao.setText("Importa\u00E7\u00E3o");
        btnImportacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnListarCartoes.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        //btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/projeto/dalvan/prbar/icones/cart-icon.png"))); // NOI18N
        btnListarCartoes.setText("Listar Cart\u00F5es");
        btnListarCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        jMenu1.setText("Principal");

        btnImportacao2.setText("Importa\u00E7\u00E3o");
        btnImportacao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJogoVelhaMouseClicked(evt);
            }
        });
        jMenu1.add(btnImportacao2);

        btnListarCartoes2.setText("Listar Cart\u00F5es");
        btnListarCartoes2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrucoMouseClicked(evt);
            }
        });
        jMenu1.add(btnListarCartoes2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(87)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(btnImportacao))
        				.addComponent(btnListarCartoes)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(44)
        					.addComponent(btnSair)))
        			.addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap(67, Short.MAX_VALUE)
        			.addComponent(btnImportacao)
        			.addGap(42)
        			.addComponent(btnListarCartoes)
        			.addGap(46)
        			.addComponent(btnSair)
        			.addGap(37))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
    	ViewArquivo view = new ViewArquivo();
		view.setTitle("Importação");
		view.setVisible(true);
		view.setLocationRelativeTo(null);
     
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
    	ViewVisualizarConciliacao view = new ViewVisualizarConciliacao();
    	view.setTitle("Cartões");
		view.setVisible(true);
		view.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnJogoVelhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJogoVelhaMouseClicked
//        JogoDaVelha jogoDaVelha = new JogoDaVelha();
//            jogoDaVelha.setVisible(true);
    }//GEN-LAST:event_btnJogoVelhaMouseClicked

    private void btnTrucoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrucoMouseClicked
//        Truco truco=new Truco();
//       truco.setVisible(true);
    }//GEN-LAST:event_btnTrucoMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImportacao;
    private javax.swing.JMenu btnImportacao2;
    private javax.swing.JButton btnListarCartoes;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenu btnListarCartoes2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}

